### ISSUE TITLE
Plan future of nunit-summary

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-summary#1]
NUnit-summary works only with NUnit V2 XML output. Also, it has been in a pre-release state for a long time. Questions:

**Should there be a 1.0 release?**

I tend to think so, at least to set a mark before adding new features.

**Should we support NUnit 3 output?**

Probably, but the real question is...

**Should NUnit3 support be built in?**

If we provide transforms equivalent to the built-in ones, they can already be used on the command line. They can also be used with NUnit3-console. What nunit-summary adds is the ability to post-process the XML output using wild-cards.

If we build the support in, we have to either have a command-line option to say which version is in use, or auto-detect by examining the XML files. Auto-detect is nicer for the users and allows mixing and matching V2 and V3 output.

@harrisonmeister Since you volunteered to help, I'm adding you as a collaborator. :-)

**Comment by harrisonmeister** [comment]
Hi @CharliePoole,

Stranglely the version I have been using is 0.25, not sure if that has any major changes, will take a look later.

> Should there be a 1.0 release?

Yes, I tend to agree. 

> Should NUnit3 support be built in?

I presume you mean should the functionality of nunit-summary be ported to nunit-console? If thats the case, I would agree as for developers using it e.g. me :) its one less dependency to have. 
Our main use case is the post-processing of the xml output, well strictly speaking the merged xml output. _(we run say 200 test libraries in a batched way since the max characters on a windows process is 32768 and generate a file for each batched run. We then merge the files back into one for post-processing)_

I think for my use-case where we would see making an additional call to _an executable_ as we do at the moment, I'd be happy for it to be auto-detected, since we would only be post-processing one (merged results) xml output file.

**Comment by CharliePoole** [comment]
Actually, I meant built-in to nunit-summary. You could currently use it with a custom transform designed for nunit 3, but it has no built-in transforms. There are four built-in transforms for nunit 2.

The ability to supply a transform on the command-line is also available in nunit3-console without any change.

**Comment by CharliePoole** [comment]
Do you use nunit-summary's wild card processing? That's the unique feature that can't readily be adopted by the console runner.

**Comment by harrisonmeister** [comment]
We dont use nunit-summary's wild card processing. It looks like we just use the plain summarising to console output (based on nunit 2 format).

The reason we used the summary executable when we were using nunit-console (in 2.6.4) is that we were calling the console a number of times, generating multiple output files and wanted one summary (hence the merging and then using the summary executable)  

I dont think the transform on the command line of nunit3's console would work currently for us, as we would want to provide the xml file to be transformed (as we do with nunit summary) and not actually run any tests (since we've already run them!)

So how we work for us at the moment

Run 1 -> Run nunit3 console -> Projects A.dll, B.dll -> output Run1.xml (nunit2 format)
Run 2 -> Run nunit3 console -> Projects C.dll, D.dll -> output Run2.xml (nunit2 format)

Run custom script to merge Run1.xml + Run2.cxml  -> mergedRuns.xml (unit2 format)

Run nunit-summary.exe mergedRuns.xml

If we can use a supplied transform to update to  nunit3 format when we get there, then that probably means we have a path forward. It just comes down to if you want to build in some Nunit3 ones and then updating the code to auto-detect it, and for people who use the wildcard that would mean no need to pass in what format the files are.

**Comment by CharliePoole** [comment]
It makes sense to start with an external transform then. Are you an XML guy?

**Comment by harrisonmeister** [comment]
Ha, unfortunately for my sins, I use a lot of XSLT in my current job (using saxon transformer) so yeh guess so!

**Comment by CharliePoole** [comment]
The four transforms in nunit-summary are the only ones I've ever written. I had hoped to escape without doing it again, which is probably why I haven't touched this one for a while. :-)

Would you be willing to create a transform or transforms for V3? Meanwhile, I'll look at how to hook them into the code. I realize that a real XSLT guru could write one transform that handles both formats, but it seems cleaner to me to select it in the C#. Would you agree?

This currently has no tests, so I'll look at that. I'm thinking just do a transform and check the output.

This started as a private project. I was in fact a user of the wild-card facility. I'm thinking it's probably time to turn it into an nunit project, so I'll probably move it over there pretty quickly. That means using issues, milestones, PRs etc. but I think that will give a bit more clarity to things like what's in each version.

BTW, the private project I devoted more time to was nunit-results, which does html reports using C# processing rather than XSLT. After doing both of them, I decided to focus on the C# approach. :-)

**Comment by CharliePoole** [comment]
@harrisonmeister How do you combine the XML result files, btw. Have you looked at what it will take to do it for V3, which has more summary fields in the top level element, as well as sub-elements that don't appear elsewhere?

**Comment by harrisonmeister** [comment]
@CharliePoole - I'd be happy to create a v3 transform. I'm probably about a day away from getting to v3 xml output (have to show business v2 working first..)

We combine each xml result file using some f# (we use FAKE to execute NUnit).For the Nunit2 format, I'm not sure how accurate its combination is (it does all kinds of aggregating etc).

The only actual info we require is a summary of all the tests than ran, the ones which failed, and the ones which were ignored/skipped. The actual timing is handled by FAKE itself with its timed targets.

**Comment by CharliePoole** [comment]
The simplest thing you could probably do for the combining would be to use the code that's already in the nunit engine. Our engine package would do it for you but would pull in a lot of references you don't need, including Mono.Cecil. So just copying source is probably the simplest.

You would need to read in each result file and create one or more TestEngineResults. You could have one big TestEngineResult with multiple results included or a separate TestEngineResult for each file. With a single TestEngineResult, there's a property that automatically gives you the combined result. With multiple results, you have to call a method to merge them, specifying the higher level element under which they should be merged. If you get to doing this, just ask for help as you need it.

**Comment by CharliePoole** [comment]
Thinking about this project... If it's eventually going to the nunit organization, it's probably easier to do it before creating branches, issues, etc. since they would all need to be re-created. I'll work on that next.

**Comment by harrisonmeister** [comment]
Thanks for the tip re TestEngineResult, i'll take a look

**Comment by CharliePoole** [comment]
Here's a conclusion to this "Plan Future" issue... @harrisonmeister @rprouse please review...
1. The nunit-summary program should move into the nunit organization. 
2. There should be a 1.0 release that incorporates present NUnit V2 functionality.
3. There should be a 2.0 release that adds the ability to process NUnit 3 output.

Details...
1. NUnit-summary allows post-processing of nunit result files using XSLT transforms. NUnit itself can do that when the test is run but not using the result files of past runs. The same transforms that would be used from the nunit3-console command-line can be used with nunit-summary.

NUnit-summary has a few added features not available from the console runner:
-  If no transform is specified, a built-in transform is used, depending on the options provided. There are four built-in transforms: full text output, full html output, brief text output and brief html output. The html is extremely simple and looks like text with a bit of highlighting.
- Wildcards can be used in the input to process multiple result files. Extended wildcard processing using "**" to match any directory is available. Output may be to a single file or to multiple files using the base name of each input file.

This all seems very complementary to nunit3-console, so I think it should move to nunit.
1. NUnit-summary has been at release 0.3 for a long time. I just advanced to 0.4 for the new work. It has been dormant because of an important learning I gained from it: I **really** dislike XSLT. However, @harrisonmeister has volunteered to help with that part and we do have an nunit-transforms project. I think we should bring this up to a release level and make it available as a separate download.

For me, release means cleaning up some of the code to match current standards and adding tests. These are likely to be functional rather than unit tests. We can run against mock-assembly and check the output. This shouldn't be too big a job.
1. @harrisonmeister is going to produce equivalent XSLT files to those already embedded in the program. We will probably play with the output to make it look more like nunit3-console output rather than V2 nunit-console output. I see this as a release 2.0.

As a side issue, it's probably a good idea to also add the internal nunit-summary tranforms to the nunit-transforms project. They emulate the output from nunit-console operating on a test result file.

Frankly, I wouldn't be offering this proposal if @harrisonmeister had not volunteered to help. Thanks!

**Comment by harrisonmeister** [comment]
@CharliePoole - looks good to me (and no problems, its nice to give something back!)

Let me know where you want me to create a PR to (once I've created the xslt's that is)
Cheers, Mark

**Comment by harrisonmeister** [comment]
@CharliePoole - I've started work on the default v3 xslt. Previously you could only have one nunit + runtime version per test-result nodes. Now they are on a test-suite in the environment node, should I aggregate them and de-dupe so the summary shows just the unique sets?

Or just get the first environment node I match?

**Comment by rprouse** [comment]
@harrisonmeister thanks for offering to help out. I think that options to create richer reports is really important. Up to now, we have been leaving that to third party support.

You ask about where to submit PR's to. I am just catching up after a long weekend, but I assume that they will be to this repository.

Going forward, I think that NUnit 3 support should be our major goal. It is hard for us as a team to push third party vendors to support the NUnit 3 XML format if we don't ourselves.

> Previously you could only have one nunit + runtime version per test-result nodes. Now they are on a test-suite in the environment node, should I aggregate them and de-dupe so the summary shows just the unique sets?

Aggregating them and de-duping them would be ideal, but don't let it delay you. We can take this in stages with aggregating as an additional enhancement later if it is easier. It is also easiest for the team to break up enhancements into smaller units to review.

**Comment by harrisonmeister** [comment]
Hi @rprouse - no worries.

I'll see what I can do on the v3 format re de-duping, I think I may have made a mistake, as I can see there is an engine-version and clr-version  on the test-run attribute. Might just be the os-version I need to de-dupe.

Having spent some time now upgrading from 2.6.4, I think taking the plunge direct to v3 (as opposed to leaving our xml results in v2 format) is definitely the way forward!

**Comment by CharliePoole** [comment]
@harrisonmeister What you are seeing is a knotty problem we have not entirely resolved ourselves. In principle, a test run may include many assemblies and each assembly may use a different .NET runtime and a different version of nunit.framework.

That was true in V2 as well, but in V2 we only reported the runtime under which **NUnit** was running, not the tests and the framework version was missing entirely.

My suggestion is to emulate the output from the NUnit 3 console. That output is different from NUnit V2 because we have much more information to report in V3. In the V3 console output we make compromises to produce a simplified report. We may want to resolve those compromises in the future but for now, I think people using the transform will expect output similar to what the console produces. Besides, having any transform that works at all will help with the work of auto-detection.

**Comment by CharliePoole** [comment]
@harrisonmeister For the present, we can't have different OS versions for different assemblies, since they all run on the same machine. That will only change when we are able to run tests remotely.

**Comment by CharliePoole** [comment]
@harrisonmeister Rob means this repository, once it is moved to the nunit organization.

I have some more work going on at my house this week, but I'll create a new repository there as soon as I have a moment. PRs should wait until then. However, you should feel free to create branches here, which I will move to nunit along with the master branch.

**Comment by harrisonmeister** [comment]
@CharliePoole - my initial output:

```
***** Merged summary

Runtime Environment 
   OS Version(s): Microsoft Windows NT 10.0.10586.0
  CLR Version(s): 4.0.30319.42000

NUnit Version(s): 3.4.1.0

Test Run Summary 
 Overall result: Success
 Test Count: 106, Passed: 106, Failed: 0, Inconclusive: 0, Skipped: 0
 Start Time: 2016-09-06 15:37:22
   End Time: 2016-09-06 15:37:22
   Duration: 2.470414 seconds
```

havent got the details of failing tests - thats something I would find useful.

I could emulate the Nunit3 console more by selecting Test filters and Run settings etc, but where we execute many tests in parallel and then merge the results this would make the summary quite bloated.

**Comment by CharliePoole** [comment]
@harrisonmeister Looks like a good start and seems the right level for our -brief option.

I hope to create the new repo later today.

**Comment by harrisonmeister** [comment]
@CharliePoole - ok thanks. I've got the test settings, test files, and failures+skipped now too as a work in progress,

**Comment by CharliePoole** [comment]
Well, that was easy! There's a Transfer button and I was able to simply transfer this repo to nunit. So now, it's nunit/nunit-summary rather than charliepoole/nunit-summary. However, it seems that the old links will all forward.

So that's step one of three for this issue. I'll set up milestones and some issues for 1.0 and 2.0 releases, although I guess if things go fast enough we can include the V3 support in the 1.0 release, eliminating the need for 2.0 for now.

**Comment by harrisonmeister** [comment]
@CharliePoole - cool. I'll start working on the other 3 xslts tomorrow. A quick side question (and totally not your codebase!), do you know if teamcity has any logs which gives more clues about importing test result files using the ##teamcity[importData type='nunit' file='E:\ba1Temp\buildTmp\tmpADFD.tmp'] syntax.

I have migrated all of our output results to v3, and using TC 9.1.6, it wont show the test tab, even though the xml reports as being imported and parsed ok.

**Comment by rprouse** [comment]
@NikolayPianikov can you help @harrisonmeister with his TeamCity questions?

**Comment by NikolayPianikov** [comment]
@harrisonmeister could you attach your xml report to test?

**Comment by harrisonmeister** [comment]
Hi @NikolayPianikov 
here is a sample - [testing-nunit3.zip](https://github.com/nunit/nunit-summary/files/459225/testing-nunit3.zip)

From what I can see on the TC 9 docs, and indeed in the XML Reporting plugin (svn trunk) it looks like the parser only supports test-results and not test-run, but I could be off the mark there.

Thanks, Mark

**Comment by NikolayPianikov** [comment]
@harrisonmeister unfortunately TC is not supporting NUnit 3 format now. TC Service Messages are used for an integration, but we have an issue in our tracker https://youtrack.jetbrains.com/issue/TW-46195

**Comment by harrisonmeister** [comment]
@NikolayPianikov thanks for the info. I'll stick to v2 format for now using the format=nunit2 for my result imports

**Comment by CharliePoole** [comment]
@harrisonmeister Be sure to vote up the TC issue! :-)

**Comment by harrisonmeister** [comment]
@CharliePoole - I will :-) plus get more voters in my organisation too!

**Comment by CharliePoole** [comment]
Hmm... I thought they had a voting mechanism, but they don't. Well, a considered comment from a user will probably help. I added one of my own.

**Comment by harrisonmeister** [comment]
Likewise, more people who talk about it the better :)

**Comment by harrisonmeister** [comment]
@CharliePoole - there is a vote option, you need to have a jetbrains account. I have upvoted :+1:

**Comment by rprouse** [comment]
@harrisonmeister I was looking at the HTML transforms and noticed that the originals escape everything. When I've written HTML transforms in the past, I included the HTML in the XSL  and even embedded XSL in the HTML which is much easier to read. Is that incorrect?

Here is a stripped version from a project I worked on. This seems much more readable and maintainable.

``` xml
<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
   <xsl:output method="html" version="4.01" encoding="UTF-8" indent="yes"/>
   <xsl:template match="/">
      <html>
         <head>
            <title>My Server - <xsl:value-of select="Index/Instance" /></title>
         </head>
         <body>>
            <div class="header">
               Server Statistics - <xsl:value-of select="Index/Instance" />
            </div>
         </body>
      </html>
   </xsl:template>
</xsl:stylesheet>
```

**Comment by harrisonmeister** [comment]
@rprouse - I am working on the html summary for v3 at the moment, and I too would normally add html in vs escaping everything. I originally thought that might be due to it being written directly to StdOut, but I think the code writes to a file in all cases.

**Comment by harrisonmeister** [comment]
Scratch that, it does write to console.out if you dont provide an output.

**Comment by CharliePoole** [comment]
That could be the reason, but I really can't remember. I wrote them about eight years ago, the first and last transforms I ever did. If we find they don't need the escaping, let's create an issue to clean it up.

**Comment by CharliePoole** [comment]
Since @harrisonmeister is moving so quickly on the NUnit 3 transforms, I no longer see the need to have two releases, postponing NUnit 3  support for the second release. I'm going to move all existing issues to the 1.0 milestone and close this design issue.

**Comment by CharliePoole** [comment]
@rprouse @harrisonmeister 
I added our standard labels and pipelines to this project.
