### ISSUE TITLE
I am trying to access Author attribute along with TestCaseSource attribute, but unable to retrieve value of author assigned to Test

### ISSUE THREAD

**Issue by SeleniumMerlinNet** [nunit/nunit-summary#20]
While trying to access Author value in TearDown i am getting null value. Do let me know if Property attribute works with TestCaseSource Attribute.
Please find below code:
` 
[TestCaseSource(typeof(TestDataMerlin), "LoginDetails", new object[] { new string[] { "TC01"} }),Author("Kalyani"),Description("Hi")]

 public void PatientEnrollment(string userDetails, LoginDetails loginDetails)
        {
            try
            {
            }
          }
`

`
  [TearDown]

public void TestCleanup()
        {
            var testCategory = TestContext.CurrentContext.Test.Properties["Author"];
        }
`

**Comment by CharliePoole** [comment]
This doesn't seem to have anything to do with the NUnit-summary project. Did you intend to post this to NUnit instead?

**Comment by SeleniumMerlinNet** [comment]
Yes Wanted to post in Nunit, sorry for the inconvenience caused.
