### ISSUE TITLE
Package nunit-summary

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-summary#4]
Decide on formats (nuget? zip?) and create packages

**Comment by CharliePoole** [comment]
@nunit/core-team @harrisonmeister 
I'm about to start working on this issue, which I left separate from the rest of the CI build because I felt we should first decide how to distribute this.

The application is a single exe, which could be distributed in a zip along with license and readme.

It could also be a nuget package, but I'm not sure that's very useful - or is it?

Thoughts?

PS: This should be my last issue, after which it's all in @harrisonmeister 's hands. :-)

**Comment by rprouse** [comment]
I don't think a NuGet package is very useful. I think we should keep this as simple as possible until we see the uptake. Zip of the EXE, License and README?

**Comment by harrisonmeister** [comment]
I agree, just a zip along with the license and readme should be fine.

**Comment by CharliePoole** [comment]
Fixed by #17
