### ISSUE TITLE
Create transforms for NUnit 3

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-summary#5]
There should be four transforms, matching the existing four functionally but written for use with NUnit 3 XML input.

**Comment by harrisonmeister** [comment]
@CharliePoole / @rprouse - the v3 Default summary xslt I am almost done with differs with the console runner output from the xml v3 output

Taking the attached screenshot:
![console-runner](https://cloud.githubusercontent.com/assets/1418993/18316343/20c67214-7512-11e6-96b4-9ad4ab2059c4.PNG)

and comparing with this output:

```
Runtime Environment 
   OS Version: Microsoft Windows NT 10.0.10586.0
  CLR Version: 4.0.30319.42000

NUnit Version: 3.4.1.0

Test Files 
    C:\Users\mark.harrison\Documents\visual studio 2015\Projects\ClassLibrary1\bin\Debug\ClassLibrary1.dll

Run Settings
    DefaultTimeout: 900000
    WorkDirectory: C:\Users\mark.harrison
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.5
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

Test Run Summary 
 Overall result: Skipped
 Test Count: 6, Passed: 2, Failed: 0, Inconclusive: 0, Skipped: 4
   Skipped Tests - Ignored: 2, Skipped: 2, Other: 0
 Start time: 2016-09-07 14:43:56Z
   End time: 2016-09-07 14:43:56Z
   Duration: 0.099475 seconds

Tests Skipped:
1) The_TEST : Some Explicit reason
2) IgnoreMe : Some Ignore reason

```

is it ok that there is a difference e.g. xml output says "Skipped", and console says "Warning" ?

_Sorry, ignore the duplicate libary in there, that was me testing duplicate entries in the xml file._

**Comment by harrisonmeister** [comment]
Also, would you like the 4 new v3 transforms embedded in the nunit-summary project for now?
If so, how do we want to call them, or do we want to detect based on the root node of the inputs e.g. test-results vs test-run ?

**Comment by CharliePoole** [comment]
For now, I'd say just use the same names as the existing ones with V3 appended. 

When we are working issue #6, it may change.

**Comment by CharliePoole** [comment]
@harrisonmeister BTW, note that our html transforms do not include the html or body elements. That's because we are sometimes creating output in a single file, sometimes in multiple files. The C# injects those elements at the start and end of each file as needed.

OTOH, if we publish these separately in the nunit-transform project we will probably want to include those elements.

**Comment by harrisonmeister** [comment]
No problems, I'll append v3 to them and exclude html and body. Adding them in later for #6 shouldn't be an issue.

**Comment by CharliePoole** [comment]
@harrisonmeister Still one transform to go right?

**Comment by harrisonmeister** [comment]
@CharliePoole - correct, I have done 3 of 4. Hopefully get the 4th (HtmlTransform-v3) done today.

**Comment by harrisonmeister** [comment]
Created PR #10 to complete HtmlTransform-v3 and updated the summary one too to be consistent.

**Comment by CharliePoole** [comment]
@harrisonmeister I believe this is done - feel free to re-open if not.
