### ISSUE TITLE
Automatically detect whether input is in NUnit 2 or 3 format

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-summary#6]
This only actually applies if the internal transforms are used. In that case, select one of the four V2 or V3 transforms depending on the options.

**Comment by CharliePoole** [comment]
I've decided to put this on hold until we have tests per issue #2.

**Comment by CharliePoole** [comment]
@harrisonmeister @rprouse
There's an issue with this line in one of the V3 transforms:

``` XML
  <xsl:preserve-space elements="*" />
```

It leads to this error:

```
1) SetUp Error : NUnit.Extras.Tests.BriefHtmlOutputTestsV3
System.Xml.Xsl.XslTransformException : White space cannot be stripped from input documents that have already been loaded. Provide the input document as an XmlReader instead.
```

That's because I am loading the input file into a document and checking it to see if if the top-level element is `<test-results>`. That was the simplest way to determine whether we are dealing with a V2 or a V3 test result. I then pass the doc as the first argument to `XslCompiledTransform.Transform`.

There are several ways we can get around this: 
- Use a reader as suggested. I'm not sure how this will work if I have already advanced the reader, however. I might need to have two of them.
- Use the doc,, close it and then have the transform re-open the file. Simple, but requires an extra read of the file.
- Get rid of the offending line. Seems to work without it - at least the tests pass - but I haven't looked at how this changes the output. The importance/unimportance of the space handling is one thing I hope @harrisonmeister can tell us.

If we drop the line in question, the existing code using an `XmlDocument` works. At first I worried that users might pass in a transform that included space-stripping, but the path for user docs is different and the problem won't arise.

I'm looking for suggestions on this before going ahead.

**Comment by harrisonmeister** [comment]
@CharliePoole - it can be safely removed. 

It was used by me in trying to get some indentation, which coincidentally I _couldnt_ get to work, and which I think has something to do with the way the xslt is loaded - but I dont think its actually that important, as the most important thing imho with the html output, is that its valid, and looks to an acceptable level.

The default value for an xslt is actually to preserve white space anyway, so the directive `<xsl:preserve-space elements="*" />` serves no useful purpose.

**Comment by CharliePoole** [comment]
@harrisonmeister OK, that's an easy choice!

The code you worked in doesn't use the XmlDocument approach - it just loads the file directly. I added the use of the document in my local copy in order to examine whether I had a V2 or a V3 item. I'll be doing a PR on that soon.

However, in case a user transform includes an `xsl:preserve-space` element, I'll make sure to have a different path for those transforms.
